# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=1, unique=True)),
                ('use_rank', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('context_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PinyinSyllable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(max_length=10)),
                ('tone', models.IntegerField()),
                ('display', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('context_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hanzi',
            name='syllables',
            field=models.ManyToManyField(to='hanzi_basics.PinyinSyllable'),
        ),
    ]
