# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 02:39
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture_name = 'hanzi_and_pinyin_syllables.json'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture_name, app_label='hanzi_basics')


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi_basics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
